# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-08-24 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20220823_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Sub',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
